# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3220ea2337c1480b0983b919f62a36bfe7828644cabbc8c29510eb7fbae530a0fea16874466019b40eb294ebcb0a59e0e3bdb7cdb4040e826a599b1adc8c8bc9

test:
  secret_key_base: fde0e8b6e703e21138f55ebf06744c11a25123fd47078e94fe04a5a4d7a3adafb35b4aa75819ef0aa0beb73e10eb7fae401e771cde1945c8ac6c0aed15e3a44f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
